name: Check format
on:
  push:
    branches: ["**"]
jobs:
  pep8_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: 'PEP8 format check'
      uses: quentinguidee/pep8-action@v1
      with:
        arguments: '--max-line-length=320'