# CI test for checking PEP8 formating
name: Python Style Checker
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  format_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Python Style Checker
      uses: andymckay/pycodestyle-action@0.1.3
      with:
        arguments: '--max-line-length=320'