name: Unit Tests

on:
  push:
    branches: [ main, joss_paper ]
  pull_request:
    branches: [ main, joss_paper ]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache conda packages
        uses: actions/cache@v3
        with:
          path: /home/runner/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('amd_env.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: amd_env.yml
          activate-environment: amd_env
          auto-activate-base: false
          use-mamba: true
      
      - name: Run pytest
        run: |
          export PYTHONPATH=$(pwd):$PYTHONPATH
          conda run -n amd_env pytest --disable-warnings -q
